name: "exoplanets-service"
controller:
    port: 8083
    ginmode: "release"
    readtimeoutmillis: 500
    writetimeoutmillis: 500
    ping: {}
service:
    ping: {}
repository:
    name: "memory" # memory/mongo
    mongo: 
        Host: localhost:27017
        Database: exoplanetservice
        UserName: bappa
        Password: bappa